# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/dialog_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editDialog(object):
    def setupUi(self, editDialog):
        editDialog.setObjectName("editDialog")
        editDialog.resize(560, 560)
        editDialog.setMinimumSize(QtCore.QSize(560, 560))
        editDialog.setMaximumSize(QtCore.QSize(560, 560))
        editDialog.setStyleSheet("QWidget {\n"
                                 "    background-color: rgb(32, 26, 25);\n"
                                 "    color: rgb(237, 224, 221);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "    background-color: rgb(255, 180, 163);\n"
                                 "    color: rgb(145, 50, 21);\n"
                                 "    border-radius: 24;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: rgb(239, 169, 153);\n"
                                 "    color: rgb(145, 50, 21);\n"
                                 "    border-radius: 24;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(217, 153, 139);\n"
                                 "    color: rgb(145, 50, 21);\n"
                                 "    border-radius: 24;\n"
                                 "}\n"
                                 "\n"
                                 "QTextEdit {\n"
                                 "    border-radius: 16;\n"
                                 "    border: 2 solid rgb(237, 224, 221);\n"
                                 "    padding: 16;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit {\n"
                                 "    border-radius: 20;\n"
                                 "    border: 2 solid rgb(237, 224, 221);\n"
                                 "    padding: 16;\n"
                                 "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(editDialog)
        self.verticalLayout.setContentsMargins(16, 32, 16, 24)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(editDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("margin-left: 16;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.titleTextEdit = QtWidgets.QLineEdit(editDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titleTextEdit.setFont(font)
        self.titleTextEdit.setObjectName("titleTextEdit")
        self.verticalLayout.addWidget(self.titleTextEdit)
        self.textTextEdit = QtWidgets.QTextEdit(editDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textTextEdit.setFont(font)
        self.textTextEdit.setObjectName("textTextEdit")
        self.verticalLayout.addWidget(self.textTextEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveBtn = QtWidgets.QPushButton(editDialog)
        self.saveBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.saveBtn.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.saveBtn.setFont(font)
        self.saveBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelBtn = QtWidgets.QPushButton(editDialog)
        self.cancelBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.cancelBtn.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(editDialog)
        QtCore.QMetaObject.connectSlotsByName(editDialog)

    def retranslateUi(self, editDialog):
        _translate = QtCore.QCoreApplication.translate
        editDialog.setWindowTitle(_translate("editDialog", "Создать"))
        self.titleLabel.setText(_translate("editDialog", "Создание заметки"))
        self.titleTextEdit.setPlaceholderText(_translate("editDialog", "Заголовок заметки"))
        self.textTextEdit.setPlaceholderText(_translate("editDialog", "Текст заметки"))
        self.saveBtn.setText(_translate("editDialog", "Сохранить"))
        self.cancelBtn.setText(_translate("editDialog", "Отмена"))
