# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/dialog_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authDialog(object):
    def setupUi(self, authDialog):
        authDialog.setObjectName("authDialog")
        authDialog.setEnabled(True)
        authDialog.resize(392, 564)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(authDialog.sizePolicy().hasHeightForWidth())
        authDialog.setSizePolicy(sizePolicy)
        authDialog.setMinimumSize(QtCore.QSize(392, 564))
        authDialog.setMaximumSize(QtCore.QSize(392, 564))
        authDialog.setStyleSheet("QWidget {\n"
                                 "    background-color: rgb(32, 26, 25);\n"
                                 "    color: rgb(237, 224, 221)\n"
                                 "}\n"
                                 "\n"
                                 "QLabel {\n"
                                 "    color: rgb(237, 224, 221);\n"
                                 "}\n"
                                 "\n"
                                 "QLabel#authTitleLabel {\n"
                                 "    color: rgb(255, 180, 163);\n"
                                 "    font-weight: 100;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit {\n"
                                 "    border: 2 solid rgb(255, 180, 163);\n"
                                 "    padding-bottom: 2;\n"
                                 "    padding-left: 16;\n"
                                 "    border-radius: 4;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "    padding: 16;\n"
                                 "    border-radius: 26;\n"
                                 "    background-color: rgb(41, 33, 32);\n"
                                 "    border: 2 solid rgb(255, 180, 163);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: rgb(66, 53, 51);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(26, 20, 20);\n"
                                 "}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(authDialog)
        self.verticalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.authTitleLabel = QtWidgets.QLabel(authDialog)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(12)
        self.authTitleLabel.setFont(font)
        self.authTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.authTitleLabel.setObjectName("authTitleLabel")
        self.horizontalLayout_2.addWidget(self.authTitleLabel)
        self.authTitleLabel_2 = QtWidgets.QLabel(authDialog)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.authTitleLabel_2.setFont(font)
        self.authTitleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.authTitleLabel_2.setObjectName("authTitleLabel_2")
        self.horizontalLayout_2.addWidget(self.authTitleLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginEdit = QtWidgets.QLineEdit(authDialog)
        self.loginEdit.setMinimumSize(QtCore.QSize(32, 48))
        self.loginEdit.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginEdit.setFont(font)
        self.loginEdit.setInputMask("")
        self.loginEdit.setMaxLength(24)
        self.loginEdit.setClearButtonEnabled(False)
        self.loginEdit.setObjectName("loginEdit")
        self.verticalLayout.addWidget(self.loginEdit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.passEdit = QtWidgets.QLineEdit(authDialog)
        self.passEdit.setMinimumSize(QtCore.QSize(32, 48))
        self.passEdit.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passEdit.setFont(font)
        self.passEdit.setInputMask("")
        self.passEdit.setMaxLength(64)
        self.passEdit.setClearButtonEnabled(False)
        self.passEdit.setObjectName("passEdit")
        self.verticalLayout.addWidget(self.passEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginBtn = QtWidgets.QPushButton(authDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginBtn.sizePolicy().hasHeightForWidth())
        self.loginBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout.addWidget(self.loginBtn)
        self.registerBtn = QtWidgets.QPushButton(authDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.registerBtn.setFont(font)
        self.registerBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerBtn.setObjectName("registerBtn")
        self.horizontalLayout.addWidget(self.registerBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)

        self.retranslateUi(authDialog)
        QtCore.QMetaObject.connectSlotsByName(authDialog)

    def retranslateUi(self, authDialog):
        _translate = QtCore.QCoreApplication.translate
        authDialog.setWindowTitle(_translate("authDialog", "SKeep - вход"))
        self.authTitleLabel.setText(_translate("authDialog", "SKeep"))
        self.authTitleLabel_2.setText(_translate("authDialog", "| Вход"))
        self.loginEdit.setToolTip(_translate("authDialog", "Введите логин"))
        self.loginEdit.setPlaceholderText(_translate("authDialog", "Логин"))
        self.passEdit.setToolTip(_translate("authDialog", "Введите логин"))
        self.passEdit.setPlaceholderText(_translate("authDialog", "Пароль"))
        self.loginBtn.setToolTip(_translate("authDialog", "Войти в приложение"))
        self.loginBtn.setText(_translate("authDialog", "Войти"))
        self.registerBtn.setToolTip(_translate("authDialog", "Регистрация в приложении"))
        self.registerBtn.setText(_translate("authDialog", "Зарегистрироваться"))
