# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/item_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemList(object):
    def setupUi(self, ItemList):
        ItemList.setObjectName("ItemList")
        ItemList.resize(588, 279)
        ItemList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        ItemList.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ItemList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleItem = QtWidgets.QLabel(ItemList)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titleItem.setFont(font)
        self.titleItem.setStyleSheet("background-color: rgb(85, 69, 18);\n"
"color: rgb(250, 224, 158);\n"
"border-radius: 24;\n"
"padding: 12;")
        self.titleItem.setObjectName("titleItem")
        self.horizontalLayout.addWidget(self.titleItem)

        self.retranslateUi(ItemList)
        QtCore.QMetaObject.connectSlotsByName(ItemList)

    def retranslateUi(self, ItemList):
        _translate = QtCore.QCoreApplication.translate
        ItemList.setWindowTitle(_translate("ItemList", "Form"))
        self.titleItem.setText(_translate("ItemList", "TextLabel"))
