# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keepMain(object):
    def setupUi(self, keepMain):
        keepMain.setObjectName("keepMain")
        keepMain.resize(980, 620)
        keepMain.setMinimumSize(QtCore.QSize(980, 620))
        keepMain.setStyleSheet("QWidget {\n"
"    background-color: rgb(32, 26, 25);\n"
"    color: rgb(237, 224, 221);\n"
"}\n"
"\n"
"QLabel#logoLabel {\n"
"    color: rgb(255, 180, 163);\n"
"}\n"
"\n"
"QWidget#mainMenu {\n"
"    background-color: rgb(41, 33, 32);\n"
"    border-radius: 8;\n"
"}\n"
"\n"
"QWidget#mainMenu QLabel {\n"
"    background-color: rgb(41, 33, 32);\n"
"}\n"
"\n"
"QWidget#viewPart {\n"
"    background-color: rgb(41, 33, 32);\n"
"    border-radius: 8;\n"
"}\n"
"\n"
"QWidget#userView {\n"
"    background-color: rgb(85, 69, 18);\n"
"    color: rgb(250, 224, 158);\n"
"    border-radius: 16;\n"
"}\n"
"\n"
"QWidget#userView QLabel {\n"
"    background-color: rgb(85, 69, 18);\n"
"    color: rgb(250, 224, 158);\n"
"}\n"
"\n"
"QWidget#userView QPushButton {\n"
"    background-color: rgb(250, 224, 158);\n"
"    color: rgb(85, 69, 18);\n"
"}\n"
"\n"
"QWidget#userView QPushButton:hover {\n"
"    background-color: rgb(250, 218, 119);\n"
"    color: rgb(85, 69, 18);\n"
"}\n"
"\n"
"QWidget#userView QPushButton:pressed {\n"
"    background-color: rgb(221, 198, 140);\n"
"    color: rgb(85, 69, 18);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 24;\n"
"    background-color: rgb(237, 224, 221);\n"
"    color: rgb(32, 26, 25);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 24;\n"
"    background-color: rgb(237, 203, 187);\n"
"    color: rgb(32, 26, 25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-radius: 24;\n"
"    background-color: rgb(207, 196, 193);\n"
"    color: rgb(32, 26, 25);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border-radius: 24;\n"
"    background-color: rgb(237, 203, 187);\n"
"    color: rgb(32, 26, 25);\n"
"}\n"
"\n"
"QWidget#viewPart QLabel {\n"
"    background-color: rgb(41, 33, 32);\n"
"}\n"
"\n"
"QWidget#viewPart QTextBrowser {\n"
"    background-color: rgb(41, 33, 32);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: rgb(41, 33, 32);\n"
"    border-radius: 8;\n"
"    border: none;\n"
"    padding: 6;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(keepMain)
        self.horizontalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainMenu = QtWidgets.QWidget(keepMain)
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainMenu)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(self.mainMenu)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.logoLabel.setFont(font)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_7.addWidget(self.logoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.userView = QtWidgets.QWidget(self.mainMenu)
        self.userView.setObjectName("userView")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.userView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userPartView = QtWidgets.QVBoxLayout()
        self.userPartView.setObjectName("userPartView")
        self.loginLabel = QtWidgets.QLabel(self.userView)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loginLabel.setFont(font)
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.userPartView.addWidget(self.loginLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.userPartView.addItem(spacerItem2)
        self.logoutBtn = QtWidgets.QPushButton(self.userView)
        self.logoutBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.logoutBtn.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logoutBtn.setFont(font)
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtn.setObjectName("logoutBtn")
        self.userPartView.addWidget(self.logoutBtn)
        self.verticalLayout.addLayout(self.userPartView)
        self.verticalLayout_7.addWidget(self.userView)
        spacerItem3 = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titlePartLabel = QtWidgets.QLabel(self.mainMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titlePartLabel.setFont(font)
        self.titlePartLabel.setObjectName("titlePartLabel")
        self.verticalLayout_2.addWidget(self.titlePartLabel)
        self.keepsBtn = QtWidgets.QPushButton(self.mainMenu)
        self.keepsBtn.setEnabled(True)
        self.keepsBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.keepsBtn.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.keepsBtn.setFont(font)
        self.keepsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.keepsBtn.setCheckable(False)
        self.keepsBtn.setChecked(False)
        self.keepsBtn.setObjectName("keepsBtn")
        self.verticalLayout_2.addWidget(self.keepsBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.usersBtn = QtWidgets.QPushButton(self.mainMenu)
        self.usersBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.usersBtn.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usersBtn.setFont(font)
        self.usersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.usersBtn.setObjectName("usersBtn")
        self.verticalLayout_2.addWidget(self.usersBtn)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.mainMenu)
        spacerItem6 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem7)
        self.mainTitleLabel = QtWidgets.QLabel(keepMain)
        self.mainTitleLabel.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.mainTitleLabel.setFont(font)
        self.mainTitleLabel.setObjectName("mainTitleLabel")
        self.verticalLayout_4.addWidget(self.mainTitleLabel)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem8)
        self.addBtn = QtWidgets.QPushButton(keepMain)
        self.addBtn.setMinimumSize(QtCore.QSize(128, 48))
        self.addBtn.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addBtn.setFont(font)
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout_4.addWidget(self.addBtn)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem9)
        self.itemsListWidget = QtWidgets.QListWidget(keepMain)
        self.itemsListWidget.setObjectName("itemsListWidget")
        self.verticalLayout_4.addWidget(self.itemsListWidget)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem12)
        self.viewTitleLabel = QtWidgets.QLabel(keepMain)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.viewTitleLabel.setFont(font)
        self.viewTitleLabel.setObjectName("viewTitleLabel")
        self.verticalLayout_6.addWidget(self.viewTitleLabel)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editBtn = QtWidgets.QPushButton(keepMain)
        self.editBtn.setMinimumSize(QtCore.QSize(128, 48))
        self.editBtn.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editBtn.setFont(font)
        self.editBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout.addWidget(self.editBtn)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.delBtn = QtWidgets.QPushButton(keepMain)
        self.delBtn.setMinimumSize(QtCore.QSize(128, 48))
        self.delBtn.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delBtn.setFont(font)
        self.delBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delBtn.setObjectName("delBtn")
        self.horizontalLayout.addWidget(self.delBtn)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem16)
        self.viewPart = QtWidgets.QWidget(keepMain)
        self.viewPart.setObjectName("viewPart")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.viewPart)
        self.verticalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.itemPartView = QtWidgets.QVBoxLayout()
        self.itemPartView.setObjectName("itemPartView")
        self.itemTitleLabel = QtWidgets.QLabel(self.viewPart)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.itemTitleLabel.setFont(font)
        self.itemTitleLabel.setObjectName("itemTitleLabel")
        self.itemPartView.addWidget(self.itemTitleLabel)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.itemPartView.addItem(spacerItem17)
        self.itemDateCreateLabel = QtWidgets.QLabel(self.viewPart)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itemDateCreateLabel.setFont(font)
        self.itemDateCreateLabel.setObjectName("itemDateCreateLabel")
        self.itemPartView.addWidget(self.itemDateCreateLabel)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.itemPartView.addItem(spacerItem18)
        self.itemTextBrowser = QtWidgets.QTextBrowser(self.viewPart)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.itemTextBrowser.setFont(font)
        self.itemTextBrowser.setObjectName("itemTextBrowser")
        self.itemPartView.addWidget(self.itemTextBrowser)
        self.verticalLayout_5.addLayout(self.itemPartView)
        self.verticalLayout_6.addWidget(self.viewPart)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem19)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)

        self.retranslateUi(keepMain)
        QtCore.QMetaObject.connectSlotsByName(keepMain)

    def retranslateUi(self, keepMain):
        _translate = QtCore.QCoreApplication.translate
        keepMain.setWindowTitle(_translate("keepMain", "SKeep"))
        self.logoLabel.setText(_translate("keepMain", "SKeep"))
        self.loginLabel.setText(_translate("keepMain", "KODASS"))
        self.logoutBtn.setText(_translate("keepMain", "Выйти"))
        self.titlePartLabel.setText(_translate("keepMain", "разделы"))
        self.keepsBtn.setText(_translate("keepMain", "Заметки"))
        self.usersBtn.setText(_translate("keepMain", "Пользователи"))
        self.mainTitleLabel.setText(_translate("keepMain", "Мои записи"))
        self.addBtn.setText(_translate("keepMain", "Добавить"))
        self.viewTitleLabel.setText(_translate("keepMain", "Просмотр"))
        self.editBtn.setText(_translate("keepMain", "Изменить"))
        self.delBtn.setText(_translate("keepMain", "Удалить"))
        self.itemTitleLabel.setText(_translate("keepMain", "Заголовок"))
        self.itemDateCreateLabel.setText(_translate("keepMain", "12-08-2020 17:42"))
        self.itemTextBrowser.setHtml(_translate("keepMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Подробное описание заметки, вернее информации, которая содержится в этой заметки. Например, тут может быть назначена встреча, записан список покупок и т д</span></p></body></html>"))
